-- Database: restaurant_db
CREATE DATABASE IF NOT EXISTS restaurant_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE restaurant_db;

-- Table: Users
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('admin', 'staff', 'customer') DEFAULT 'customer',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: Menu
CREATE TABLE IF NOT EXISTS menu (
    menu_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    image VARCHAR(255),
    status TINYINT(1) DEFAULT 1, -- 1=Available, 0=Unavailable
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: Restaurant Tables
CREATE TABLE IF NOT EXISTS tables (
    table_id INT AUTO_INCREMENT PRIMARY KEY,
    table_name VARCHAR(50) NOT NULL UNIQUE,
    status ENUM('available', 'occupied') DEFAULT 'available'
);

-- Table: Orders
CREATE TABLE IF NOT EXISTS orders (
    order_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    table_id INT,
    total_price DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    status ENUM('pending', 'cooking', 'served', 'completed', 'cancelled') DEFAULT 'pending',
    payment_method ENUM('cash', 'qr') DEFAULT 'cash',
    payment_status ENUM('pending', 'paid') DEFAULT 'pending',
    order_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (table_id) REFERENCES tables(table_id) ON DELETE SET NULL
);

-- Table: Order Items
CREATE TABLE IF NOT EXISTS order_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT NOT NULL,
    menu_id INT NOT NULL,
    qty INT NOT NULL DEFAULT 1,
    price DECIMAL(10, 2) NOT NULL, -- Price at the time of order
    FOREIGN KEY (order_id) REFERENCES orders(order_id) ON DELETE CASCADE,
    FOREIGN KEY (menu_id) REFERENCES menu(menu_id)
);

-- Seed Data: Users (Password: 123456)
-- Note: In a real app, passwords should be hashed. We will use password_hash() in PHP.
-- For this seed, we'll insert a raw hash for '123456' generated by PHP's password_hash().
-- Hash for '123456' is usually '$2y$10$...' but for simplicity in this raw SQL we might need to rely on the PHP registration to create valid users, 
-- OR we can insert a known hash. Let's assume the user will register or we provide a default admin.
-- Default Admin: admin@example.com / 123456
INSERT INTO users (name, email, password, role) VALUES 
('Admin User', 'admin@example.com', '$2y$10$iI09Y1hmxmO54efdst/cReKy18pfoIKGuuMfKvfyzXWQ47Z2bU.1e', 'admin'),
('Staff User', 'staff@example.com', '$2y$10$iI09Y1hmxmO54efdst/cReKy18pfoIKGuuMfKvfyzXWQ47Z2bU.1e', 'staff');

-- Seed Data: Tables
INSERT INTO tables (table_name) VALUES ('Table 1'), ('Table 2'), ('Table 3'), ('Table 4'), ('Table 5');

-- Seed Data: Menu
INSERT INTO menu (name, price, status) VALUES 
('Pad Thai', 50.00, 1),
('Fried Rice', 45.00, 1),
('Tom Yum Kung', 120.00, 1),
('Green Curry', 80.00, 1);
